### ISSUE TITLE
"join our community" link not working

### ISSUE THREAD

**Issue by Free-Radical** [uesleibros/OpenGPT#1]
```
404 - page not found
The 

main
 branch of 

OpenGPT
 does not contain the path 

discord.gg/W7tnxxA6mG.
```

**Comment by uesleibros** [comment]
> ```
> 404 - page not found
> The 
> 
> main
>  branch of 
> 
> OpenGPT
>  does not contain the path 
> 
> discord.gg/W7tnxxA6mG.
> ```

Try this: https://discord.gg/byWqZfAs9D
