### ISSUE TITLE
Change in code?

### ISSUE THREAD

**Issue by VincentNeemie** [uesleibros/OpenGPT#3]
Greetings. 

A few days ago i wrote a google colab and was working to make some ui on cloud for this... nothing is working now, the discord link in the repo readme, doesnt seem to work either?

https://github.com/uesleibros/OpenGPT/blob/main/discord.gg/W7tnxxA6mG

**Comment by VincentNeemie** [comment]
Welp, i guess this is for me to learn, to branch out haha...

**Comment by uesleibros** [comment]
Just copy the discord link and join
